//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BFF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Account.
        /// </summary>
        public static string Account_CreateNew {
            get {
                return ResourceManager.GetString("Account_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the account and all of its transactions, two-sided transfers will become one-sided, and the account-specific outflows in budgeting will disappear.
        ///
        ///Are you really sure? (A backup will be created automatically, if you would like to rewind the data afterwards).
        /// </summary>
        public static string Account_Delete_ConfirmationMessage {
            get {
                return ResourceManager.GetString("Account_Delete_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Accounts.
        /// </summary>
        public static string Account_Edit {
            get {
                return ResourceManager.GetString("Account_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Balance.
        /// </summary>
        public static string Account_StartingBalance {
            get {
                return ResourceManager.GetString("Account_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        public static string Account_StartingDate {
            get {
                return ResourceManager.GetString("Account_StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Accounts.
        /// </summary>
        public static string AccountTabsView_AllAccounts {
            get {
                return ResourceManager.GetString("AccountTabsView_AllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AccountTabsView_NewAccount_Create {
            get {
                return ResourceManager.GetString("AccountTabsView_NewAccount_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string AccountView_Column_Transfer {
            get {
                return ResourceManager.GetString("AccountView_Column_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AccountView_ConMenu_Delete {
            get {
                return ResourceManager.GetString("AccountView_ConMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountView_Header_Account {
            get {
                return ResourceManager.GetString("AccountView_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AccountView_Header_Category {
            get {
                return ResourceManager.GetString("AccountView_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Number.
        /// </summary>
        public static string AccountView_Header_CheckNumber {
            get {
                return ResourceManager.GetString("AccountView_Header_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string AccountView_Header_Cleared {
            get {
                return ResourceManager.GetString("AccountView_Header_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AccountView_Header_Date {
            get {
                return ResourceManager.GetString("AccountView_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string AccountView_Header_Flag {
            get {
                return ResourceManager.GetString("AccountView_Header_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string AccountView_Header_Memo {
            get {
                return ResourceManager.GetString("AccountView_Header_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee.
        /// </summary>
        public static string AccountView_Header_Payee {
            get {
                return ResourceManager.GetString("AccountView_Header_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string AccountView_Header_Sum {
            get {
                return ResourceManager.GetString("AccountView_Header_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string AccountView_Header_SymbolAbbr {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string AccountView_Header_SymbolAbbr_Tooltip {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the table.
        /// </summary>
        public static string AccountView_ToolTip_AddToTable {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_AddToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New splitted Transaction.
        /// </summary>
        public static string AccountView_ToolTip_NewParentTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewParentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Transaction.
        /// </summary>
        public static string AccountView_ToolTip_NewTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Transfer.
        /// </summary>
        public static string AccountView_ToolTip_NewTransfer {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Budgeting_Available {
            get {
                return ResourceManager.GetString("Budgeting_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which is available in this month but not assigned to any category yet..
        /// </summary>
        public static string Budgeting_AvailableExplanation {
            get {
                return ResourceManager.GetString("Budgeting_AvailableExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Budgeting_Balance {
            get {
                return ResourceManager.GetString("Budgeting_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgeted.
        /// </summary>
        public static string Budgeting_Budgeted {
            get {
                return ResourceManager.GetString("Budgeting_Budgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of all amounts of money which are budgeted on a category in this month..
        /// </summary>
        public static string Budgeting_BudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_BudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Budgeting_Income {
            get {
                return ResourceManager.GetString("Budgeting_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of earned money which is assigned for the expenses of this month..
        /// </summary>
        public static string Budgeting_IncomeExplanation {
            get {
                return ResourceManager.GetString("Budgeting_IncomeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Budgeted.
        /// </summary>
        public static string Budgeting_NotBudgeted {
            get {
                return ResourceManager.GetString("Budgeting_NotBudgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which was available last month but not assigned to any category..
        /// </summary>
        public static string Budgeting_NotBudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_NotBudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Sided Transfers.
        /// </summary>
        public static string Budgeting_OneSidedTransfers {
            get {
                return ResourceManager.GetString("Budgeting_OneSidedTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Sided Transfers may occur after a deletion of an account. They have to be considered, because they are not neutral to the budget..
        /// </summary>
        public static string Budgeting_OneSidedTransfersExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OneSidedTransfersExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outflows.
        /// </summary>
        public static string Budgeting_Outflows {
            get {
                return ResourceManager.GetString("Budgeting_Outflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overbudgeted.
        /// </summary>
        public static string Budgeting_Overbudgeted {
            get {
                return ResourceManager.GetString("Budgeting_Overbudgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which was missing to satisfy all categories in last month..
        /// </summary>
        public static string Budgeting_OverbudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverbudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which is missing to satisfy all categories in this month..
        /// </summary>
        public static string Budgeting_OverbudgetedThisMonthExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverbudgetedThisMonthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overspend.
        /// </summary>
        public static string Budgeting_Overspend {
            get {
                return ResourceManager.GetString("Budgeting_Overspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of overspend amounts of money accumulated from all categories in last month..
        /// </summary>
        public static string Budgeting_OverspendExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverspendExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmationDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        public static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new payee.
        /// </summary>
        public static string CreateNewPayee {
            get {
                return ResourceManager.GetString("CreateNewPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new category is not allowed to be empty!.
        /// </summary>
        public static string ErrorMessageCategoryNameEmpty {
            get {
                return ResourceManager.GetString("ErrorMessageCategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyCategory {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A payee has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyPayee {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new account&apos;s name isn&apos;t allowed to be empty or match a name of the existing accounts!.
        /// </summary>
        public static string ErrorMessageWrongAccountName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists on the chosen category level!.
        /// </summary>
        public static string ErrorMessageWrongCategoryName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category level already contains a category of chosen name!.
        /// </summary>
        public static string ErrorMessageWrongCategoryParent {
            get {
                return ResourceManager.GetString("ErrorMessageWrongCategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a new payee isn&apos;t allowed to be empty or an already existing one..
        /// </summary>
        public static string ErrorMessageWrongPayeeName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongPayeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; could not be found..
        /// </summary>
        public static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string General_Long {
            get {
                return ResourceManager.GetString("General_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string General_Negative {
            get {
                return ResourceManager.GetString("General_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string General_Positive {
            get {
                return ResourceManager.GetString("General_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        public static string General_Short {
            get {
                return ResourceManager.GetString("General_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string HamburgerMenu_Accounts {
            get {
                return ResourceManager.GetString("HamburgerMenu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string HamburgerMenu_Budget {
            get {
                return ResourceManager.GetString("HamburgerMenu_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ImportView_Browse {
            get {
                return ResourceManager.GetString("ImportView_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ImportView_Cancel {
            get {
                return ResourceManager.GetString("ImportView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportView_Import {
            get {
                return ResourceManager.GetString("ImportView_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and save to this path:.
        /// </summary>
        public static string ImportView_SaveFile {
            get {
                return ResourceManager.GetString("ImportView_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a YNAB4 CSV-file.
        /// </summary>
        public static string ImportView_YNAB4 {
            get {
                return ResourceManager.GetString("ImportView_YNAB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the YNAB Budget CSV:.
        /// </summary>
        public static string ImportView_YNAB4_Budget {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the YNAB Transaction CSV:.
        /// </summary>
        public static string ImportView_YNAB4_Transaction {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MainWindow_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_File_New {
            get {
                return ResourceManager.GetString("MainWindow_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindow_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new category.
        /// </summary>
        public static string NameOfNewCategory {
            get {
                return ResourceManager.GetString("NameOfNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new payee.
        /// </summary>
        public static string NameOfNewPayee {
            get {
                return ResourceManager.GetString("NameOfNewPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Relevant?.
        /// </summary>
        public static string NewCategory_IsIncomeRelevant {
            get {
                return ResourceManager.GetString("NewCategory_IsIncomeRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Offset.
        /// </summary>
        public static string NewCategory_MonthOffset {
            get {
                return ResourceManager.GetString("NewCategory_MonthOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFF budget plan (*.sqlite)|*.sqlite.
        /// </summary>
        public static string OpenSaveDialog_Filter {
            get {
                return ResourceManager.GetString("OpenSaveDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Budget Plan.
        /// </summary>
        public static string OpenSaveDialog_TitleNew {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Budget Plan.
        /// </summary>
        public static string OpenSaveDialog_TitleOpen {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accents.
        /// </summary>
        public static string Settings_Accents {
            get {
                return ResourceManager.GetString("Settings_Accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency format.
        /// </summary>
        public static string Settings_Currency {
            get {
                return ResourceManager.GetString("Settings_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string Settings_Date {
            get {
                return ResourceManager.GetString("Settings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Category.
        /// </summary>
        public static string SuperiorCategory {
            get {
                return ResourceManager.GetString("SuperiorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text could not be parsed as a currency!.
        /// </summary>
        public static string ValidationRule_Currency {
            get {
                return ResourceManager.GetString("ValidationRule_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is out of range: [ {0} .. {1} ]!.
        /// </summary>
        public static string ValidationRule_CurrencyLongRange {
            get {
                return ResourceManager.GetString("ValidationRule_CurrencyLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input field may not be empty!.
        /// </summary>
        public static string ValidationRule_NoNull {
            get {
                return ResourceManager.GetString("ValidationRule_NoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file path does not exist!.
        /// </summary>
        public static string ValidationRule_NotExistingFilePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory of the save path does not exist!.
        /// </summary>
        public static string ValidationRule_NotExistingSavePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name of this save path is empty!.
        /// </summary>
        public static string ValidationRule_NotExistingSavePath_EmptyName {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath_EmptyName", resourceCulture);
            }
        }
    }
}
