//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BFF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountTabsView_AllAccounts {
            get {
                return ResourceManager.GetString("AccountTabsView_AllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountTabsView_NewAccount_Create {
            get {
                return ResourceManager.GetString("AccountTabsView_NewAccount_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountTabsView_NewAccount_Name {
            get {
                return ResourceManager.GetString("AccountTabsView_NewAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountTabsView_NewAccount_StartingBalance {
            get {
                return ResourceManager.GetString("AccountTabsView_NewAccount_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Balance {
            get {
                return ResourceManager.GetString("AccountView_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Column_Transfer {
            get {
                return ResourceManager.GetString("AccountView_Column_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ConMenu_Delete {
            get {
                return ResourceManager.GetString("AccountView_ConMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Account {
            get {
                return ResourceManager.GetString("AccountView_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Category {
            get {
                return ResourceManager.GetString("AccountView_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Cleared {
            get {
                return ResourceManager.GetString("AccountView_Header_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Date {
            get {
                return ResourceManager.GetString("AccountView_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Memo {
            get {
                return ResourceManager.GetString("AccountView_Header_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Payee {
            get {
                return ResourceManager.GetString("AccountView_Header_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_Sum {
            get {
                return ResourceManager.GetString("AccountView_Header_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_Header_SymbolAbbr {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_StartingBalance {
            get {
                return ResourceManager.GetString("AccountView_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ToolTip_AddToTable {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_AddToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ToolTip_NewIncome {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ToolTip_NewParentIncome {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewParentIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ToolTip_NewParentTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewParentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ToolTip_NewTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountView_ToolTip_NewTransfer {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_Browse {
            get {
                return ResourceManager.GetString("ImportView_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_Cancel {
            get {
                return ResourceManager.GetString("ImportView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_Import {
            get {
                return ResourceManager.GetString("ImportView_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_SaveFile {
            get {
                return ResourceManager.GetString("ImportView_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_YNAB4 {
            get {
                return ResourceManager.GetString("ImportView_YNAB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_YNAB4_Budget {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportView_YNAB4_Transaction {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_File_New {
            get {
                return ResourceManager.GetString("MainWindow_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Accents {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Currency {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Currency_Negative {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Currency_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Currency_Positive {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Currency_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Date {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Date_Long {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Date_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Date_Long_Inverted {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Date_Long_Inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Date_Short {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Date_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Language {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Settings_Theme {
            get {
                return ResourceManager.GetString("MainWindow_Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenSaveDialog_Filter {
            get {
                return ResourceManager.GetString("OpenSaveDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenSaveDialog_TitleNew {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenSaveDialog_TitleOpen {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationRule_Currency {
            get {
                return ResourceManager.GetString("ValidationRule_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationRule_CurrencyLongRange {
            get {
                return ResourceManager.GetString("ValidationRule_CurrencyLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationRule_NoNull {
            get {
                return ResourceManager.GetString("ValidationRule_NoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationRule_NotExistingFilePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationRule_NotExistingSavePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationRule_NotExistingSavePath_EmptyName {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath_EmptyName", resourceCulture);
            }
        }
    }
}
