//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFF.View.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BFF.ViewModel.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontostand.
        /// </summary>
        internal static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Konto erstellen.
        /// </summary>
        internal static string Account_CreateNew {
            get {
                return ResourceManager.GetString("Account_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies wird das Konto und all ihre Transaktionen löschen, vollständige Transfers werden einseitig und die kontenspezifischen Ausgabe beim Budget werden verschwinden.
        ///
        ///Bist Du dir wirklich sicher? (Ein automatisches Backup wird hergestellt um es möglich zu machen auf den Stand vor der Löschung zurückzusetzen).
        /// </summary>
        internal static string Account_Delete_ConfirmationMessage {
            get {
                return ResourceManager.GetString("Account_Delete_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konten bearbeiten.
        /// </summary>
        internal static string Account_Edit {
            get {
                return ResourceManager.GetString("Account_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoname.
        /// </summary>
        internal static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfangskontostand.
        /// </summary>
        internal static string Account_StartingBalance {
            get {
                return ResourceManager.GetString("Account_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfangsdatum.
        /// </summary>
        internal static string Account_StartingDate {
            get {
                return ResourceManager.GetString("Account_StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Konten.
        /// </summary>
        internal static string AccountTabsView_AllAccounts {
            get {
                return ResourceManager.GetString("AccountTabsView_AllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string AccountTabsView_NewAccount_Create {
            get {
                return ResourceManager.GetString("AccountTabsView_NewAccount_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breche Abzielen ab.
        /// </summary>
        internal static string AccountView_AbortTargetingBalance {
            get {
                return ResourceManager.GetString("AccountView_AbortTargetingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles.
        /// </summary>
        internal static string AccountView_Balance_All {
            get {
                return ResourceManager.GetString("AccountView_Balance_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigt.
        /// </summary>
        internal static string AccountView_Balance_Cleared {
            get {
                return ResourceManager.GetString("AccountView_Balance_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell.
        /// </summary>
        internal static string AccountView_Balance_Current {
            get {
                return ResourceManager.GetString("AccountView_Balance_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt.
        /// </summary>
        internal static string AccountView_Balance_Total {
            get {
                return ResourceManager.GetString("AccountView_Balance_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerledigt.
        /// </summary>
        internal static string AccountView_Balance_Uncleared {
            get {
                return ResourceManager.GetString("AccountView_Balance_Uncleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string AccountView_Column_Transfer {
            get {
                return ResourceManager.GetString("AccountView_Column_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string AccountView_ConMenu_Delete {
            get {
                return ResourceManager.GetString("AccountView_ConMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne.
        /// </summary>
        internal static string AccountView_ConMenu_Remove {
            get {
                return ResourceManager.GetString("AccountView_ConMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle den ersten Konteneintrag.
        /// </summary>
        internal static string AccountView_FirstEntry {
            get {
                return ResourceManager.GetString("AccountView_FirstEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        internal static string AccountView_Header_Account {
            get {
                return ResourceManager.GetString("AccountView_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string AccountView_Header_Category {
            get {
                return ResourceManager.GetString("AccountView_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schecknummer.
        /// </summary>
        internal static string AccountView_Header_CheckNumber {
            get {
                return ResourceManager.GetString("AccountView_Header_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigt.
        /// </summary>
        internal static string AccountView_Header_Cleared {
            get {
                return ResourceManager.GetString("AccountView_Header_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string AccountView_Header_Date {
            get {
                return ResourceManager.GetString("AccountView_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string AccountView_Header_Flag {
            get {
                return ResourceManager.GetString("AccountView_Header_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz.
        /// </summary>
        internal static string AccountView_Header_Memo {
            get {
                return ResourceManager.GetString("AccountView_Header_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsempfänger.
        /// </summary>
        internal static string AccountView_Header_Payee {
            get {
                return ResourceManager.GetString("AccountView_Header_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        internal static string AccountView_Header_Sum {
            get {
                return ResourceManager.GetString("AccountView_Header_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string AccountView_Header_SymbolAbbr {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string AccountView_Header_SymbolAbbr_Tooltip {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwischensumme.
        /// </summary>
        internal static string AccountView_IntermediateBalance {
            get {
                return ResourceManager.GetString("AccountView_IntermediateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlender Betrag.
        /// </summary>
        internal static string AccountView_MissingSum {
            get {
                return ResourceManager.GetString("AccountView_MissingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setze Ziel-Kontostand.
        /// </summary>
        internal static string AccountView_SetTargetBalance {
            get {
                return ResourceManager.GetString("AccountView_SetTargetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel-Kontostand.
        /// </summary>
        internal static string AccountView_TargetBalance {
            get {
                return ResourceManager.GetString("AccountView_TargetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichert die gerade bearbeiteten Elemente zum Konto.
        /// </summary>
        internal static string AccountView_ToolTip_AddToTable {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_AddToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt eine neue aufgeteilte Ausgabe.
        /// </summary>
        internal static string AccountView_ToolTip_NewParentTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewParentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt eine neue Ausgabe.
        /// </summary>
        internal static string AccountView_ToolTip_NewTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt eine neue Umbuchung.
        /// </summary>
        internal static string AccountView_ToolTip_NewTransfer {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbar.
        /// </summary>
        internal static string Budgeting_Available {
            get {
                return ResourceManager.GetString("Budgeting_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Geldmenge, die diesen Monat gegeben ist, jedoch noch in keiner Kategorie verbucht wurde..
        /// </summary>
        internal static string Budgeting_AvailableExplanation {
            get {
                return ResourceManager.GetString("Budgeting_AvailableExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        internal static string Budgeting_Balance {
            get {
                return ResourceManager.GetString("Budgeting_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbucht.
        /// </summary>
        internal static string Budgeting_Budgeted {
            get {
                return ResourceManager.GetString("Budgeting_Budgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe aller Gelder, die diesen Monat Kategorien zugewiesen sind..
        /// </summary>
        internal static string Budgeting_BudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_BudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Ausgaben der letzten drei Monate.
        /// </summary>
        internal static string Budgeting_ContextMenu_AvgOutflowsLastThreeMonths {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_AvgOutflowsLastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Ausgaben des letzten Jahres.
        /// </summary>
        internal static string Budgeting_ContextMenu_AvgOutflowsLastYear {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_AvgOutflowsLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo zu null.
        /// </summary>
        internal static string Budgeting_ContextMenu_BalanceToZero {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_BalanceToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgetwert des letzten Monats.
        /// </summary>
        internal static string Budgeting_ContextMenu_BudgetLastMonth {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_BudgetLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgaben des letzten Monats.
        /// </summary>
        internal static string Budgeting_ContextMenu_OutflowsLastMonth {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_OutflowsLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string Budgeting_ContextMenu_Zero {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkünfte.
        /// </summary>
        internal static string Budgeting_Income {
            get {
                return ResourceManager.GetString("Budgeting_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdiente Geldmenge, die für die Ausgaben diesen Monats zugewiesen wurde..
        /// </summary>
        internal static string Budgeting_IncomeExplanation {
            get {
                return ResourceManager.GetString("Budgeting_IncomeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fülle alle Budgetzellen mit:.
        /// </summary>
        internal static string Budgeting_Month_ContextMenu_AllCellsHeader {
            get {
                return ResourceManager.GetString("Budgeting_Month_ContextMenu_AllCellsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fülle alle leeren Budgetzellen mit:.
        /// </summary>
        internal static string Budgeting_Month_ContextMenu_EmptyCellsHeader {
            get {
                return ResourceManager.GetString("Budgeting_Month_ContextMenu_EmptyCellsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht Verbucht.
        /// </summary>
        internal static string Budgeting_NotBudgeted {
            get {
                return ResourceManager.GetString("Budgeting_NotBudgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Geldmenge, die letzten Monat gegeben war, jedoch in keiner Kategorie verbucht wurde..
        /// </summary>
        internal static string Budgeting_NotBudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_NotBudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einseitige Transfers.
        /// </summary>
        internal static string Budgeting_OneSidedTransfers {
            get {
                return ResourceManager.GetString("Budgeting_OneSidedTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einseitige Transfers können nach der Löschung eines Kontos auftauchen. Sie müssen berücksichtigt werden, weil sie nicht neutral für die Buchhaltung sind..
        /// </summary>
        internal static string Budgeting_OneSidedTransfersExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OneSidedTransfersExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgaben.
        /// </summary>
        internal static string Budgeting_Outflows {
            get {
                return ResourceManager.GetString("Budgeting_Outflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überbucht.
        /// </summary>
        internal static string Budgeting_Overbudgeted {
            get {
                return ResourceManager.GetString("Budgeting_Overbudgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Geldmenge, die letzten Monat fehlte um alle Kategorien zu erfüllen..
        /// </summary>
        internal static string Budgeting_OverbudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverbudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Geldmenge, die diesen Monat fehlt um alle Kategorien zu erfüllen..
        /// </summary>
        internal static string Budgeting_OverbudgetedThisMonthExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverbudgetedThisMonthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreitung.
        /// </summary>
        internal static string Budgeting_Overspend {
            get {
                return ResourceManager.GetString("Budgeting_Overspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe der Budgetüberschreitungen aufsummiert über alle Kategorien letzten Monats..
        /// </summary>
        internal static string Budgeting_OverspendExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverspendExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtsummen anzeigen.
        /// </summary>
        internal static string Budgeting_ShowAggregates {
            get {
                return ResourceManager.GetString("Budgeting_ShowAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht-zugewiesen.
        /// </summary>
        internal static string Budgeting_UnassignedTransactions {
            get {
                return ResourceManager.GetString("Budgeting_UnassignedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Summe aller Transaktionen, die keine Kategorie zugewiesen haben..
        /// </summary>
        internal static string Budgeting_UnassignedTransactionsExplanation {
            get {
                return ResourceManager.GetString("Budgeting_UnassignedTransactionsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Kategorie erstellen.
        /// </summary>
        internal static string Category_CreateNew {
            get {
                return ResourceManager.GetString("Category_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        internal static string Common_Configuration {
            get {
                return ResourceManager.GetString("Common_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge.
        /// </summary>
        internal static string Common_Entries {
            get {
                return ResourceManager.GetString("Common_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass die Kategorie &quot;{0}&quot; gelöscht werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmCategoryDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass die Kategorie &quot;{0}&quot; in die Kategorie &quot;{1}&quot; zusammengeführt werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmCategoryMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmCategoryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass die Markierung &quot;{0}&quot; gelöscht werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmFlagDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmFlagDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass die Markierung &quot;{0}&quot; in die Markierung &quot;{1}&quot; zusammengeführt werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmFlagMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmFlagMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass die Einkommenskategorie &quot;{0}&quot; gelöscht werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmIncomeCategoryDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmIncomeCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass die Einkommenskategorie &quot;{0}&quot; in die Einkommenskategorie &quot;{1}&quot; zusammengeführt werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmIncomeCategoryMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmIncomeCategoryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass der Zahlungsempfänger &quot;{0}&quot; gelöscht werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmPayeeDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmPayeeDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher, dass der Zahlungsempfänger &quot;{0}&quot; in den Zahlungsempfänger &quot;{1}&quot; zusammengeführt werden soll?.
        /// </summary>
        internal static string ConfirmationDialog_ConfirmPayeeMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmPayeeMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist Du dir sicher?.
        /// </summary>
        internal static string ConfirmationDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle eine neue Kategorie.
        /// </summary>
        internal static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle eine neue Markierung.
        /// </summary>
        internal static string CreateNewFlag {
            get {
                return ResourceManager.GetString("CreateNewFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle einen neuen Bezahlten.
        /// </summary>
        internal static string CreateNewPayee {
            get {
                return ResourceManager.GetString("CreateNewPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Erstellen der Einträge ist ein Fehler aufgetreten. Überprüfe die Konfiguration..
        /// </summary>
        internal static string CsvBankStatementImport_ErrorDuringItemsCreation {
            get {
                return ResourceManager.GetString("CsvBankStatementImport_ErrorDuringItemsCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoauszug.
        /// </summary>
        internal static string Domain_BankStatement {
            get {
                return ResourceManager.GetString("Domain_BankStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien.
        /// </summary>
        internal static string Domain_Categories {
            get {
                return ResourceManager.GetString("Domain_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markierungen.
        /// </summary>
        internal static string Domain_Flags {
            get {
                return ResourceManager.GetString("Domain_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkommenskategorien.
        /// </summary>
        internal static string Domain_IncomeCategories {
            get {
                return ResourceManager.GetString("Domain_IncomeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoauszug öffnen.
        /// </summary>
        internal static string Domain_OpenBankStatement {
            get {
                return ResourceManager.GetString("Domain_OpenBankStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsempfänger.
        /// </summary>
        internal static string Domain_Payees {
            get {
                return ResourceManager.GetString("Domain_Payees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Konto muss ausgewählt werden bevor der Eintrag hinzugefügt wird..
        /// </summary>
        internal static string ErrorMessage_AccountHasToBeChosen {
            get {
                return ResourceManager.GetString("ErrorMessage_AccountHasToBeChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name einer neuen Kategorie darf nicht leer sein!.
        /// </summary>
        internal static string ErrorMessageCategoryNameEmpty {
            get {
                return ResourceManager.GetString("ErrorMessageCategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Konto muss ausgewählt werden..
        /// </summary>
        internal static string ErrorMessageEmptyAccount {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Kategorie muss ausgewählt werden..
        /// </summary>
        internal static string ErrorMessageEmptyCategory {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Quellkonto muss ausgewählt werden..
        /// </summary>
        internal static string ErrorMessageEmptyFromAccount {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Bezahlter muss ausgewählt werden..
        /// </summary>
        internal static string ErrorMessageEmptyPayee {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Zielkonto muss ausgewählt werden.
        /// </summary>
        internal static string ErrorMessageEmptyToAccount {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem Kontennamen ist es nicht erlaubt leer zu sein oder den Namen eines bestehendem Kontos zu gleichen..
        /// </summary>
        internal static string ErrorMessageWrongAccountName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Name existiert bereits für die gewählte Kategorieebene!.
        /// </summary>
        internal static string ErrorMessageWrongCategoryName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dieser Kategorieebene existiert bereits eine Kategorie mit gewählten Namen!.
        /// </summary>
        internal static string ErrorMessageWrongCategoryParent {
            get {
                return ResourceManager.GetString("ErrorMessageWrongCategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name einer neuen Markierung darf nicht leer sein oder bereit existieren..
        /// </summary>
        internal static string ErrorMessageWrongFlagName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongFlagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name eines neuen Bezahlten darf nicht leer sein oder bereit existieren..
        /// </summary>
        internal static string ErrorMessageWrongPayeeName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongPayeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &quot;{0}&quot; konnte nicht gefunden werden..
        /// </summary>
        internal static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Markierung erstellen.
        /// </summary>
        internal static string Flag_CreateNew {
            get {
                return ResourceManager.GetString("Flag_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markierungen bearbeiten.
        /// </summary>
        internal static string Flag_Edit {
            get {
                return ResourceManager.GetString("Flag_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datumsformat.
        /// </summary>
        internal static string General_DateFormat {
            get {
                return ResourceManager.GetString("General_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennzeichen.
        /// </summary>
        internal static string General_Delimiter {
            get {
                return ResourceManager.GetString("General_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateipfad.
        /// </summary>
        internal static string General_FilePath {
            get {
                return ResourceManager.GetString("General_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopfdaten.
        /// </summary>
        internal static string General_Header {
            get {
                return ResourceManager.GetString("General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        internal static string General_Long {
            get {
                return ResourceManager.GetString("General_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizformat.
        /// </summary>
        internal static string General_MemoFormat {
            get {
                return ResourceManager.GetString("General_MemoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negativ.
        /// </summary>
        internal static string General_Negative {
            get {
                return ResourceManager.GetString("General_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle einen neuen Zahlungsempfänger wenn er nicht existiert?.
        /// </summary>
        internal static string General_NewPayeeIfNotExisting {
            get {
                return ResourceManager.GetString("General_NewPayeeIfNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string General_Okay {
            get {
                return ResourceManager.GetString("General_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsempfängerformat.
        /// </summary>
        internal static string General_PayeeFormat {
            get {
                return ResourceManager.GetString("General_PayeeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positiv.
        /// </summary>
        internal static string General_Positive {
            get {
                return ResourceManager.GetString("General_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string General_Profile {
            get {
                return ResourceManager.GetString("General_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil entfernen.
        /// </summary>
        internal static string General_RemoveProfile {
            get {
                return ResourceManager.GetString("General_RemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil zurücksetzen.
        /// </summary>
        internal static string General_ResetProfile {
            get {
                return ResourceManager.GetString("General_ResetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Profil speichern.
        /// </summary>
        internal static string General_SaveNewProfile {
            get {
                return ResourceManager.GetString("General_SaveNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil speichern.
        /// </summary>
        internal static string General_SaveProfile {
            get {
                return ResourceManager.GetString("General_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurz.
        /// </summary>
        internal static string General_Short {
            get {
                return ResourceManager.GetString("General_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betragsformat.
        /// </summary>
        internal static string General_SumFormat {
            get {
                return ResourceManager.GetString("General_SumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht zugewiesen.
        /// </summary>
        internal static string General_Unassigned {
            get {
                return ResourceManager.GetString("General_Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konten.
        /// </summary>
        internal static string HamburgerMenu_Accounts {
            get {
                return ResourceManager.GetString("HamburgerMenu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string HamburgerMenu_Budget {
            get {
                return ResourceManager.GetString("HamburgerMenu_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        internal static string ImportView_Browse {
            get {
                return ResourceManager.GetString("ImportView_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string ImportView_Cancel {
            get {
                return ResourceManager.GetString("ImportView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportziel.
        /// </summary>
        internal static string ImportView_ExportKind {
            get {
                return ResourceManager.GetString("ImportView_ExportKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importieren.
        /// </summary>
        internal static string ImportView_Import {
            get {
                return ResourceManager.GetString("ImportView_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importquelle.
        /// </summary>
        internal static string ImportView_ImportKind {
            get {
                return ResourceManager.GetString("ImportView_ImportKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string ImportView_Password {
            get {
                return ResourceManager.GetString("ImportView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importiere und speichere unter folgendem Pfad:.
        /// </summary>
        internal static string ImportView_SaveFile {
            get {
                return ResourceManager.GetString("ImportView_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importkonfiguration.
        /// </summary>
        internal static string ImportView_Title {
            get {
                return ResourceManager.GetString("ImportView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad zu der YNAB-Budget-CSV:.
        /// </summary>
        internal static string ImportView_YNAB4_Budget {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad zu der YNAB-Transaktions-CSV:.
        /// </summary>
        internal static string ImportView_YNAB4_Transaction {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konvertiere zu.
        /// </summary>
        internal static string Label_ConvertTo {
            get {
                return ResourceManager.GetString("Label_ConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch kein Buchhaltungsprojekt geladen.
        ///Um ein Projekt zu erstellen, öffnen oder importieren
        ///öffne das Datei-Menü in der Ecke oben links..
        /// </summary>
        internal static string MainWindow_Empty {
            get {
                return ResourceManager.GetString("MainWindow_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        internal static string MainWindow_File_Close {
            get {
                return ResourceManager.GetString("MainWindow_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string MainWindow_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string MainWindow_File_New {
            get {
                return ResourceManager.GetString("MainWindow_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        internal static string MainWindow_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der neuen Kategorie.
        /// </summary>
        internal static string NameOfNewCategory {
            get {
                return ResourceManager.GetString("NameOfNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der neuen Markierung.
        /// </summary>
        internal static string NameOfNewFlag {
            get {
                return ResourceManager.GetString("NameOfNewFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des neuen Bezahlten.
        /// </summary>
        internal static string NameOfNewPayee {
            get {
                return ResourceManager.GetString("NameOfNewPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn angehakt, dann erstellt dies eine Einkommenskategorie.
        ///Nur Transaktionen, die zu so einer Kategorie angehängt sind, werden als Einkommen interpretiert..
        /// </summary>
        internal static string NewCategory_IncomeRelevantExplanation {
            get {
                return ResourceManager.GetString("NewCategory_IncomeRelevantExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkommensrelevant?.
        /// </summary>
        internal static string NewCategory_IsIncomeRelevant {
            get {
                return ResourceManager.GetString("NewCategory_IsIncomeRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatsversatz.
        /// </summary>
        internal static string NewCategory_MonthOffset {
            get {
                return ResourceManager.GetString("NewCategory_MonthOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFF Finanzplan (*.realm)|*.realm|BFF Finanzplan (*.bffs,*.sqlite)|*bffs;*.sqlite.
        /// </summary>
        internal static string OpenSaveDialog_Filter {
            get {
                return ResourceManager.GetString("OpenSaveDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle einen neuen Finanzplan.
        /// </summary>
        internal static string OpenSaveDialog_TitleNew {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne einen Finanzplan.
        /// </summary>
        internal static string OpenSaveDialog_TitleOpen {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktueller Betrag.
        /// </summary>
        internal static string ParentTransEditingView_CurrentSum {
            get {
                return ResourceManager.GetString("ParentTransEditingView_CurrentSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwischensumme.
        /// </summary>
        internal static string ParentTransEditingView_IntermediateSum {
            get {
                return ResourceManager.GetString("ParentTransEditingView_IntermediateSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlender Betrag.
        /// </summary>
        internal static string ParentTransEditingView_MissingSumWithoutSubs {
            get {
                return ResourceManager.GetString("ParentTransEditingView_MissingSumWithoutSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlender Betrag exklusive der uneingereichten Einträge.
        /// </summary>
        internal static string ParentTransEditingView_MissingSumWithSubs {
            get {
                return ResourceManager.GetString("ParentTransEditingView_MissingSumWithSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Zahlungsempfänger erstellen.
        /// </summary>
        internal static string Payee_CreateNew {
            get {
                return ResourceManager.GetString("Payee_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsempfänger bearbeiten.
        /// </summary>
        internal static string Payee_Edit {
            get {
                return ResourceManager.GetString("Payee_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichere neuen Budget-Plan zu:.
        /// </summary>
        internal static string SaveNewBudgetPlanTo {
            get {
                return ResourceManager.GetString("SaveNewBudgetPlanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzente.
        /// </summary>
        internal static string Settings_Accents {
            get {
                return ResourceManager.GetString("Settings_Accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immer Spaltentitel in der Editiertabelle ausblenden.
        /// </summary>
        internal static string Settings_AlwaysHideEditHeaders {
            get {
                return ResourceManager.GetString("Settings_AlwaysHideEditHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währungsformat.
        /// </summary>
        internal static string Settings_Currency {
            get {
                return ResourceManager.GetString("Settings_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datumsformat.
        /// </summary>
        internal static string Settings_Date {
            get {
                return ResourceManager.GetString("Settings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Schecknummern.
        /// </summary>
        internal static string Settings_ShowCheckNumbers {
            get {
                return ResourceManager.GetString("Settings_ShowCheckNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Markierungen.
        /// </summary>
        internal static string Settings_ShowFlags {
            get {
                return ResourceManager.GetString("Settings_ShowFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übergestellte Kategorie.
        /// </summary>
        internal static string SuperiorCategory {
            get {
                return ResourceManager.GetString("SuperiorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Texts_de_o_resx {
            get {
                return ResourceManager.GetString("Texts.de.o.resx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Gesamtkontostand unter Berücksichtigung der Einträge mit einem zukünftigen Datum.
        ///Schaue in den Tooltip für eine bessere Unterscheidung..
        /// </summary>
        internal static string ToolTip_Account_Balance {
            get {
                return ResourceManager.GetString("ToolTip_Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zwischensumme bezieht die Einträge, die noch gespeichert werden müssen, mit ein..
        /// </summary>
        internal static string ToolTip_Account_IntermediateBalance {
            get {
                return ResourceManager.GetString("ToolTip_Account_IntermediateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Differenz von dem Zielkontostands und der Zwischensumme..
        /// </summary>
        internal static string ToolTip_Account_MissingSum {
            get {
                return ResourceManager.GetString("ToolTip_Account_MissingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das setzen des Zielkontostands erlaubt die automatische Berechnung der fehlenden Summe..
        /// </summary>
        internal static string ToolTip_Account_SetTargetBalance {
            get {
                return ResourceManager.GetString("ToolTip_Account_SetTargetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kontostand des Kontos am eingestellten Startdatum..
        /// </summary>
        internal static string ToolTip_Account_StartingBalance {
            get {
                return ResourceManager.GetString("ToolTip_Account_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn die Gesamtsummen aktiviert sind, dann werden die Werte der Unterkategorien zu dem eigenen Wert draufaddiert..
        /// </summary>
        internal static string ToolTip_BudgetOverview_Aggregates {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_Aggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutze diesen Datumselektor um zu einem beliebigen Monat zu springen (der Tag ist nicht von Belang)..
        /// </summary>
        internal static string ToolTip_BudgetOverview_JumpToMonth {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_JumpToMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschiebe um einen Monat zurück.
        /// </summary>
        internal static string ToolTip_BudgetOverview_ShiftMonthBackward {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_ShiftMonthBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschiebe um einen Monat vor.
        /// </summary>
        internal static string ToolTip_BudgetOverview_ShiftMonthForward {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_ShiftMonthForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Monatsversatz verschiebt monatsweise den Zeitpunkt zu wann das Einkommen aktiv wird.
        ///Zum Beispiel ein Monatsversatz von eins verschiebt das Einkommen zum nächsten Monat und Minus eins zum vorigen Monat..
        /// </summary>
        internal static string ToolTip_Category_MonthOffset {
            get {
                return ResourceManager.GetString("ToolTip_Category_MonthOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn eine übergeordnete Kategorie gewählt wird, dann wird die neue Kategorie ihr als Unterkategorie angehangen..
        /// </summary>
        internal static string ToolTip_Category_SuperiorCategory {
            get {
                return ResourceManager.GetString("ToolTip_Category_SuperiorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücke den Knopf in dieser Spalte um das Element der zugehörigen Reihe zu löschen..
        /// </summary>
        internal static string ToolTip_DeleteRow {
            get {
                return ResourceManager.GetString("ToolTip_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um eine Kategorie mit einer anderen zusammenzuführen, sollte das Symbol aus dieser Spalte von der Quellreihe gezogen und auf die Zielreihe losgelassen werden.
        ///Die Ziel-Kategorie übernimmt alle Konteneinträge und Unterkategorien von der Quell-Kategorie.
        ///Wenn ein Paar der Unterkategorien den selben Namen haben, dann wird die Unterkategorie der Quelle automatisch umbenannt (Zahl angehangen)..
        /// </summary>
        internal static string ToolTip_MergeToCategory {
            get {
                return ResourceManager.GetString("ToolTip_MergeToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um eine Markierung mit einer anderen zusammenzuführen, sollte das Symbol aus dieser Spalte von der Quellreihe gezogen und auf die Zielreihe losgelassen werden.
        ///Die Ziel-Markierung übernimmt alle Konteneinträge von der Quell-Markierung und behält ihre eigene Farbe bei..
        /// </summary>
        internal static string ToolTip_MergeToFlag {
            get {
                return ResourceManager.GetString("ToolTip_MergeToFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um eine Einkommenskategorie mit einer anderen zusammenzuführen, sollte das Symbol aus dieser Spalte von der Quellreihe gezogen und auf die Zielreihe losgelassen werden.
        ///Die Ziel-Einkommenskategorie übernimmt alle Konteneinträge von der Quell-Einkommenskategorie und behält den Monatsversatz bei..
        /// </summary>
        internal static string ToolTip_MergeToIncomeCategory {
            get {
                return ResourceManager.GetString("ToolTip_MergeToIncomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um einen Zahlungsempfänger mit einer anderen zusammenzuführen, sollte das Symbol aus dieser Spalte von der Quellreihe gezogen und auf die Zielreihe losgelassen werden.
        ///Der Ziel-Zahlungsempfänger übernimmt alle Konteneinträge von dem Quell-Zahlungsempfänger..
        /// </summary>
        internal static string ToolTip_MergeToPayee {
            get {
                return ResourceManager.GetString("ToolTip_MergeToPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quellkonto.
        /// </summary>
        internal static string ToolTip_Symbol_FromAccount {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkommenskategory.
        /// </summary>
        internal static string ToolTip_Symbol_IncomeCategory {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_IncomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkommenstransaktion.
        /// </summary>
        internal static string ToolTip_Symbol_IncomeTransaction {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_IncomeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke um die Teiltransaktionen zu sehen und zu bearbeiten..
        /// </summary>
        internal static string ToolTip_Symbol_SplitTransaction {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_SplitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zielkonto.
        /// </summary>
        internal static string ToolTip_Symbol_ToAccount {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion.
        /// </summary>
        internal static string ToolTip_Symbol_Transaction {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string ToolTip_Symbol_Transfer {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Konto dem der Eintrag gehört..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Account {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kategorie bestimmt deinen persönlichen Zweck von diesem Eintrag.
        ///Weil die Kategorien hierarchisch aufgebaut werden können, wird der ganze hierarchische Pfad im Tooltip angezeigt.
        ///
        ///Wenn der Eintrag ein Transfer ist, dann wird hier das Zielkonto eingetragen..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Category {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn nötig kann hier die Checknummer eingetragen werden..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_CheckNumber {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Haken kann genutzt werden um erledigte Einträgen von welchen die noch Überarbeitung benötigen zu unterscheiden.
        ///Die Gesamtsummen können im Tooltip vom Kontostand betrachtet werden..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Cleared {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum an dem der Eintrag wirksam ist..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Date {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Markierung hebt den Eintrag visuell durch die Farbe hervor und ist komplett optional..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Flag {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Notiz ist dazu bestimmt dem Eintrag eine beliebige Beschreibung zu geben..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Memo {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die bezahlte oder die bezahlende Person wird hier eingetragen.
        ///
        ///Wenn der Eintrag ein Transfer ist, dann wird hier das Quellkonto eingetragen..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Payee {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Symbole zeigen von welchem Typ der Konteneintrag ist..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_S {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Einkommenseintrag markiert eine Transaktion, die als Einkommen betrachtet wird..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_S_Income {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Transaktion lässt Geld aus oder in ein Konto fließen..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_S_Transaction {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Transfer überträgt Geld von einem Konto in das andere..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_S_Transfer {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Summe des Eintrags..
        /// </summary>
        internal static string ToolTip_TransGrid_Header_Sum {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Text konnte nicht als Währung geparst werden!.
        /// </summary>
        internal static string ValidationRule_Currency {
            get {
                return ResourceManager.GetString("ValidationRule_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert liegt außerhalb des Gültigkeitsbereiches: [ {0} .. {1} ]!.
        /// </summary>
        internal static string ValidationRule_CurrencyLongRange {
            get {
                return ResourceManager.GetString("ValidationRule_CurrencyLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Eingabefeld darf nicht leer bleiben!.
        /// </summary>
        internal static string ValidationRule_NoNull {
            get {
                return ResourceManager.GetString("ValidationRule_NoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Dateipfad existiert nicht!.
        /// </summary>
        internal static string ValidationRule_NotExistingFilePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Verzeichnis vom Speicherpfad existiert nicht!.
        /// </summary>
        internal static string ValidationRule_NotExistingSavePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dateiname von diesem Speicherpfad ist leer!.
        /// </summary>
        internal static string ValidationRule_NotExistingSavePath_EmptyName {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath_EmptyName", resourceCulture);
            }
        }
    }
}
