//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFF.View.Avalonia.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Wpf.Properties.Texts.ru-RU", typeof(Texts_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сальдо счёта.
        /// </summary>
        public static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Account.
        /// </summary>
        public static string Account_CreateNew {
            get {
                return ResourceManager.GetString("Account_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the account and all of its transactions, two-sided transfers will become one-sided, and the account-specific outflows in budgeting will disappear.
        ///
        ///Are you really sure? (A backup will be created automatically, if you would like to rewind the data afterwards).
        /// </summary>
        public static string Account_Delete_ConfirmationMessage {
            get {
                return ResourceManager.GetString("Account_Delete_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Accounts.
        /// </summary>
        public static string Account_Edit {
            get {
                return ResourceManager.GetString("Account_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название счета.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальное сальдо счёта.
        /// </summary>
        public static string Account_StartingBalance {
            get {
                return ResourceManager.GetString("Account_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        public static string Account_StartingDate {
            get {
                return ResourceManager.GetString("Account_StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все счета.
        /// </summary>
        public static string AccountTabsView_AllAccounts {
            get {
                return ResourceManager.GetString("AccountTabsView_AllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string AccountTabsView_NewAccount_Create {
            get {
                return ResourceManager.GetString("AccountTabsView_NewAccount_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort targeting balance.
        /// </summary>
        public static string AccountView_AbortTargetingBalance {
            get {
                return ResourceManager.GetString("AccountView_AbortTargetingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AccountView_Balance_All {
            get {
                return ResourceManager.GetString("AccountView_Balance_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string AccountView_Balance_Cleared {
            get {
                return ResourceManager.GetString("AccountView_Balance_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string AccountView_Balance_Current {
            get {
                return ResourceManager.GetString("AccountView_Balance_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string AccountView_Balance_Total {
            get {
                return ResourceManager.GetString("AccountView_Balance_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncleared.
        /// </summary>
        public static string AccountView_Balance_Uncleared {
            get {
                return ResourceManager.GetString("AccountView_Balance_Uncleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод.
        /// </summary>
        public static string AccountView_Column_Transfer {
            get {
                return ResourceManager.GetString("AccountView_Column_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string AccountView_ConMenu_Delete {
            get {
                return ResourceManager.GetString("AccountView_ConMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string AccountView_ConMenu_Remove {
            get {
                return ResourceManager.GetString("AccountView_ConMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create first account entry.
        /// </summary>
        public static string AccountView_FirstEntry {
            get {
                return ResourceManager.GetString("AccountView_FirstEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счёт.
        /// </summary>
        public static string AccountView_Header_Account {
            get {
                return ResourceManager.GetString("AccountView_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string AccountView_Header_Category {
            get {
                return ResourceManager.GetString("AccountView_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Number.
        /// </summary>
        public static string AccountView_Header_CheckNumber {
            get {
                return ResourceManager.GetString("AccountView_Header_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнено.
        /// </summary>
        public static string AccountView_Header_Cleared {
            get {
                return ResourceManager.GetString("AccountView_Header_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string AccountView_Header_Date {
            get {
                return ResourceManager.GetString("AccountView_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string AccountView_Header_Flag {
            get {
                return ResourceManager.GetString("AccountView_Header_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметка.
        /// </summary>
        public static string AccountView_Header_Memo {
            get {
                return ResourceManager.GetString("AccountView_Header_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель платежа.
        /// </summary>
        public static string AccountView_Header_Payee {
            get {
                return ResourceManager.GetString("AccountView_Header_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string AccountView_Header_Sum {
            get {
                return ResourceManager.GetString("AccountView_Header_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string AccountView_Header_SymbolAbbr {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип операции.
        /// </summary>
        public static string AccountView_Header_SymbolAbbr_Tooltip {
            get {
                return ResourceManager.GetString("AccountView_Header_SymbolAbbr_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate balance.
        /// </summary>
        public static string AccountView_IntermediateBalance {
            get {
                return ResourceManager.GetString("AccountView_IntermediateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing sum.
        /// </summary>
        public static string AccountView_MissingSum {
            get {
                return ResourceManager.GetString("AccountView_MissingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set target balance.
        /// </summary>
        public static string AccountView_SetTargetBalance {
            get {
                return ResourceManager.GetString("AccountView_SetTargetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target balance.
        /// </summary>
        public static string AccountView_TargetBalance {
            get {
                return ResourceManager.GetString("AccountView_TargetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persists currently edited elements to the account.
        /// </summary>
        public static string AccountView_ToolTip_AddToTable {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_AddToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new split transaction.
        /// </summary>
        public static string AccountView_ToolTip_NewParentTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewParentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new transaction.
        /// </summary>
        public static string AccountView_ToolTip_NewTransaction {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new transfer.
        /// </summary>
        public static string AccountView_ToolTip_NewTransfer {
            get {
                return ResourceManager.GetString("AccountView_ToolTip_NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Budgeting_Available {
            get {
                return ResourceManager.GetString("Budgeting_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which is available in this month but not assigned to any category yet..
        /// </summary>
        public static string Budgeting_AvailableExplanation {
            get {
                return ResourceManager.GetString("Budgeting_AvailableExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Budgeting_Balance {
            get {
                return ResourceManager.GetString("Budgeting_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgeted.
        /// </summary>
        public static string Budgeting_Budgeted {
            get {
                return ResourceManager.GetString("Budgeting_Budgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of all amounts of money which are budgeted on a category in this month..
        /// </summary>
        public static string Budgeting_BudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_BudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average outflows of the last three months.
        /// </summary>
        public static string Budgeting_ContextMenu_AvgOutflowsLastThreeMonths {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_AvgOutflowsLastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average outflows of the last year.
        /// </summary>
        public static string Budgeting_ContextMenu_AvgOutflowsLastYear {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_AvgOutflowsLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance to zero.
        /// </summary>
        public static string Budgeting_ContextMenu_BalanceToZero {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_BalanceToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget values from last month.
        /// </summary>
        public static string Budgeting_ContextMenu_BudgetLastMonth {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_BudgetLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outflows of last month.
        /// </summary>
        public static string Budgeting_ContextMenu_OutflowsLastMonth {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_OutflowsLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        public static string Budgeting_ContextMenu_Zero {
            get {
                return ResourceManager.GetString("Budgeting_ContextMenu_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Budgeting_Income {
            get {
                return ResourceManager.GetString("Budgeting_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of earned money which is assigned for the expenses of this month..
        /// </summary>
        public static string Budgeting_IncomeExplanation {
            get {
                return ResourceManager.GetString("Budgeting_IncomeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all budget cells with:.
        /// </summary>
        public static string Budgeting_Month_ContextMenu_AllCellsHeader {
            get {
                return ResourceManager.GetString("Budgeting_Month_ContextMenu_AllCellsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all empty budget cells with:.
        /// </summary>
        public static string Budgeting_Month_ContextMenu_EmptyCellsHeader {
            get {
                return ResourceManager.GetString("Budgeting_Month_ContextMenu_EmptyCellsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Budgeted.
        /// </summary>
        public static string Budgeting_NotBudgeted {
            get {
                return ResourceManager.GetString("Budgeting_NotBudgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which was available last month but not assigned to any category..
        /// </summary>
        public static string Budgeting_NotBudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_NotBudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Sided Transfers.
        /// </summary>
        public static string Budgeting_OneSidedTransfers {
            get {
                return ResourceManager.GetString("Budgeting_OneSidedTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Sided Transfers may occur after a deletion of an account. They have to be considered, because they are not neutral to the budget..
        /// </summary>
        public static string Budgeting_OneSidedTransfersExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OneSidedTransfersExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outflows.
        /// </summary>
        public static string Budgeting_Outflows {
            get {
                return ResourceManager.GetString("Budgeting_Outflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overbudgeted.
        /// </summary>
        public static string Budgeting_Overbudgeted {
            get {
                return ResourceManager.GetString("Budgeting_Overbudgeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which was missing to satisfy all categories in last month..
        /// </summary>
        public static string Budgeting_OverbudgetedExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverbudgetedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money which is missing to satisfy all categories in this month..
        /// </summary>
        public static string Budgeting_OverbudgetedThisMonthExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverbudgetedThisMonthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overspend.
        /// </summary>
        public static string Budgeting_Overspend {
            get {
                return ResourceManager.GetString("Budgeting_Overspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of overspend amounts of money accumulated from all categories in last month..
        /// </summary>
        public static string Budgeting_OverspendExplanation {
            get {
                return ResourceManager.GetString("Budgeting_OverspendExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Aggregates.
        /// </summary>
        public static string Budgeting_ShowAggregates {
            get {
                return ResourceManager.GetString("Budgeting_ShowAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string Budgeting_UnassignedTransactions {
            get {
                return ResourceManager.GetString("Budgeting_UnassignedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of all transactions, which have no category assigned..
        /// </summary>
        public static string Budgeting_UnassignedTransactionsExplanation {
            get {
                return ResourceManager.GetString("Budgeting_UnassignedTransactionsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Category.
        /// </summary>
        public static string Category_CreateNew {
            get {
                return ResourceManager.GetString("Category_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Common_Configuration {
            get {
                return ResourceManager.GetString("Common_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string Common_Entries {
            get {
                return ResourceManager.GetString("Common_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the category &quot;{0}&quot; should be deleted?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmCategoryDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the category &quot;{0}&quot; should get merged into the category &quot;{1}&quot;?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmCategoryMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmCategoryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the flag &quot;{0}&quot; should be deleted?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmFlagDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmFlagDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the flag &quot;{0}&quot; should get merged into the flag &quot;{1}&quot;?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmFlagMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmFlagMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the income category &quot;{0}&quot; should be deleted?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmIncomeCategoryDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmIncomeCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the income category &quot;{0}&quot; should get merged into the income category &quot;{1}&quot;?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmIncomeCategoryMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmIncomeCategoryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the payee &quot;{0}&quot; should be deleted?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmPayeeDeletion {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmPayeeDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that the payee &quot;{0}&quot; should get merged into the payee &quot;{1}&quot;?.
        /// </summary>
        public static string ConfirmationDialog_ConfirmPayeeMerge {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ConfirmPayeeMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmationDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        public static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new flag.
        /// </summary>
        public static string CreateNewFlag {
            get {
                return ResourceManager.GetString("CreateNewFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new payee.
        /// </summary>
        public static string CreateNewPayee {
            get {
                return ResourceManager.GetString("CreateNewPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the entries. Check the configuration..
        /// </summary>
        public static string CsvBankStatementImport_ErrorDuringItemsCreation {
            get {
                return ResourceManager.GetString("CsvBankStatementImport_ErrorDuringItemsCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Statement.
        /// </summary>
        public static string Domain_BankStatement {
            get {
                return ResourceManager.GetString("Domain_BankStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Domain_Categories {
            get {
                return ResourceManager.GetString("Domain_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Domain_Flags {
            get {
                return ResourceManager.GetString("Domain_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Categories.
        /// </summary>
        public static string Domain_IncomeCategories {
            get {
                return ResourceManager.GetString("Domain_IncomeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bank Statement.
        /// </summary>
        public static string Domain_OpenBankStatement {
            get {
                return ResourceManager.GetString("Domain_OpenBankStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payees.
        /// </summary>
        public static string Domain_Payees {
            get {
                return ResourceManager.GetString("Domain_Payees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account has to be chosen before the entry is inserted..
        /// </summary>
        public static string ErrorMessage_AccountHasToBeChosen {
            get {
                return ResourceManager.GetString("ErrorMessage_AccountHasToBeChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new category is not allowed to be empty!.
        /// </summary>
        public static string ErrorMessageCategoryNameEmpty {
            get {
                return ResourceManager.GetString("ErrorMessageCategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyAccount {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyCategory {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A source-account has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyFromAccount {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A payee has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyPayee {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A target-account has to be chosen..
        /// </summary>
        public static string ErrorMessageEmptyToAccount {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new account&apos;s name isn&apos;t allowed to be empty or match a name of the existing accounts!.
        /// </summary>
        public static string ErrorMessageWrongAccountName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists on the chosen category level!.
        /// </summary>
        public static string ErrorMessageWrongCategoryName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category level already contains a category of chosen name!.
        /// </summary>
        public static string ErrorMessageWrongCategoryParent {
            get {
                return ResourceManager.GetString("ErrorMessageWrongCategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a new flag isn&apos;t allowed to be empty or an already existing one..
        /// </summary>
        public static string ErrorMessageWrongFlagName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongFlagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a new payee isn&apos;t allowed to be empty or an already existing one..
        /// </summary>
        public static string ErrorMessageWrongPayeeName {
            get {
                return ResourceManager.GetString("ErrorMessageWrongPayeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл  &quot;{0}&quot; не найден..
        /// </summary>
        public static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Flag.
        /// </summary>
        public static string Flag_CreateNew {
            get {
                return ResourceManager.GetString("Flag_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flags.
        /// </summary>
        public static string Flag_Edit {
            get {
                return ResourceManager.GetString("Flag_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string General_DateFormat {
            get {
                return ResourceManager.GetString("General_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string General_Delimiter {
            get {
                return ResourceManager.GetString("General_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string General_FilePath {
            get {
                return ResourceManager.GetString("General_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string General_Header {
            get {
                return ResourceManager.GetString("General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная.
        /// </summary>
        public static string General_Long {
            get {
                return ResourceManager.GetString("General_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Format.
        /// </summary>
        public static string General_MemoFormat {
            get {
                return ResourceManager.GetString("General_MemoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положительно.
        /// </summary>
        public static string General_Negative {
            get {
                return ResourceManager.GetString("General_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new payee if not existing?.
        /// </summary>
        public static string General_NewPayeeIfNotExisting {
            get {
                return ResourceManager.GetString("General_NewPayeeIfNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string General_Okay {
            get {
                return ResourceManager.GetString("General_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee Format.
        /// </summary>
        public static string General_PayeeFormat {
            get {
                return ResourceManager.GetString("General_PayeeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отрицательно.
        /// </summary>
        public static string General_Positive {
            get {
                return ResourceManager.GetString("General_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string General_Profile {
            get {
                return ResourceManager.GetString("General_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Profile.
        /// </summary>
        public static string General_RemoveProfile {
            get {
                return ResourceManager.GetString("General_RemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Profile.
        /// </summary>
        public static string General_ResetProfile {
            get {
                return ResourceManager.GetString("General_ResetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new Profile.
        /// </summary>
        public static string General_SaveNewProfile {
            get {
                return ResourceManager.GetString("General_SaveNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        public static string General_SaveProfile {
            get {
                return ResourceManager.GetString("General_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткая.
        /// </summary>
        public static string General_Short {
            get {
                return ResourceManager.GetString("General_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Format.
        /// </summary>
        public static string General_SumFormat {
            get {
                return ResourceManager.GetString("General_SumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string General_Unassigned {
            get {
                return ResourceManager.GetString("General_Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string HamburgerMenu_Accounts {
            get {
                return ResourceManager.GetString("HamburgerMenu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string HamburgerMenu_Budget {
            get {
                return ResourceManager.GetString("HamburgerMenu_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор....
        /// </summary>
        public static string ImportView_Browse {
            get {
                return ResourceManager.GetString("ImportView_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string ImportView_Cancel {
            get {
                return ResourceManager.GetString("ImportView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Target.
        /// </summary>
        public static string ImportView_ExportKind {
            get {
                return ResourceManager.GetString("ImportView_ExportKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импортировать.
        /// </summary>
        public static string ImportView_Import {
            get {
                return ResourceManager.GetString("ImportView_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Source.
        /// </summary>
        public static string ImportView_ImportKind {
            get {
                return ResourceManager.GetString("ImportView_ImportKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ImportView_Password {
            get {
                return ResourceManager.GetString("ImportView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить по следующему пути:.
        /// </summary>
        public static string ImportView_SaveFile {
            get {
                return ResourceManager.GetString("ImportView_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Configuration.
        /// </summary>
        public static string ImportView_Title {
            get {
                return ResourceManager.GetString("ImportView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к YNAB-Budget-CSV:.
        /// </summary>
        public static string ImportView_YNAB4_Budget {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к YNAB-Transaktions-CSV:.
        /// </summary>
        public static string ImportView_YNAB4_Transaction {
            get {
                return ResourceManager.GetString("ImportView_YNAB4_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to.
        /// </summary>
        public static string Label_ConvertTo {
            get {
                return ResourceManager.GetString("Label_ConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программe.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No budget project loaded yet.
        ///In order to create, open or import a project
        ///open the File-menu in the upper left corner..
        /// </summary>
        public static string MainWindow_Empty {
            get {
                return ResourceManager.GetString("MainWindow_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainWindow_File_Close {
            get {
                return ResourceManager.GetString("MainWindow_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт.
        /// </summary>
        public static string MainWindow_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string MainWindow_File_New {
            get {
                return ResourceManager.GetString("MainWindow_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string MainWindow_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new category.
        /// </summary>
        public static string NameOfNewCategory {
            get {
                return ResourceManager.GetString("NameOfNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new flag.
        /// </summary>
        public static string NameOfNewFlag {
            get {
                return ResourceManager.GetString("NameOfNewFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new payee.
        /// </summary>
        public static string NameOfNewPayee {
            get {
                return ResourceManager.GetString("NameOfNewPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, then an income category is created.
        ///Only transactions assigned to such a category are interpreted as income..
        /// </summary>
        public static string NewCategory_IncomeRelevantExplanation {
            get {
                return ResourceManager.GetString("NewCategory_IncomeRelevantExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Relevant?.
        /// </summary>
        public static string NewCategory_IsIncomeRelevant {
            get {
                return ResourceManager.GetString("NewCategory_IsIncomeRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Offset.
        /// </summary>
        public static string NewCategory_MonthOffset {
            get {
                return ResourceManager.GetString("NewCategory_MonthOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFF финансовый план (*.realm)|*.realm|BFF финансовый план (*.bffs,*.sqlite)|*bffs;*.sqlite.
        /// </summary>
        public static string OpenSaveDialog_Filter {
            get {
                return ResourceManager.GetString("OpenSaveDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый финасовый план.
        /// </summary>
        public static string OpenSaveDialog_TitleNew {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть финасовый план.
        /// </summary>
        public static string OpenSaveDialog_TitleOpen {
            get {
                return ResourceManager.GetString("OpenSaveDialog_TitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Sum.
        /// </summary>
        public static string ParentTransEditingView_CurrentSum {
            get {
                return ResourceManager.GetString("ParentTransEditingView_CurrentSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate sum.
        /// </summary>
        public static string ParentTransEditingView_IntermediateSum {
            get {
                return ResourceManager.GetString("ParentTransEditingView_IntermediateSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Sum.
        /// </summary>
        public static string ParentTransEditingView_MissingSumWithoutSubs {
            get {
                return ResourceManager.GetString("ParentTransEditingView_MissingSumWithoutSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Sum exlusively unsubmitted entries.
        /// </summary>
        public static string ParentTransEditingView_MissingSumWithSubs {
            get {
                return ResourceManager.GetString("ParentTransEditingView_MissingSumWithSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Payee.
        /// </summary>
        public static string Payee_CreateNew {
            get {
                return ResourceManager.GetString("Payee_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payees.
        /// </summary>
        public static string Payee_Edit {
            get {
                return ResourceManager.GetString("Payee_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new budget plan to:.
        /// </summary>
        public static string SaveNewBudgetPlanTo {
            get {
                return ResourceManager.GetString("SaveNewBudgetPlanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string Settings_Accents {
            get {
                return ResourceManager.GetString("Settings_Accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always hide column headers of the editing table.
        /// </summary>
        public static string Settings_AlwaysHideEditHeaders {
            get {
                return ResourceManager.GetString("Settings_AlwaysHideEditHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат валюты.
        /// </summary>
        public static string Settings_Currency {
            get {
                return ResourceManager.GetString("Settings_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат даты.
        /// </summary>
        public static string Settings_Date {
            get {
                return ResourceManager.GetString("Settings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Check Numbers.
        /// </summary>
        public static string Settings_ShowCheckNumbers {
            get {
                return ResourceManager.GetString("Settings_ShowCheckNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Flags.
        /// </summary>
        public static string Settings_ShowFlags {
            get {
                return ResourceManager.GetString("Settings_ShowFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Category.
        /// </summary>
        public static string SuperiorCategory {
            get {
                return ResourceManager.GetString("SuperiorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The overall balance including entries with a date in future.
        ///See tooltip for better distinction..
        /// </summary>
        public static string ToolTip_Account_Balance {
            get {
                return ResourceManager.GetString("ToolTip_Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intermediate balance includes the entries which have to be saved yet..
        /// </summary>
        public static string ToolTip_Account_IntermediateBalance {
            get {
                return ResourceManager.GetString("ToolTip_Account_IntermediateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference of the target balance and the intermediate balance..
        /// </summary>
        public static string ToolTip_Account_MissingSum {
            get {
                return ResourceManager.GetString("ToolTip_Account_MissingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the target balance enables the automatic calculation of the missing sum..
        /// </summary>
        public static string ToolTip_Account_SetTargetBalance {
            get {
                return ResourceManager.GetString("ToolTip_Account_SetTargetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance of the account on the setup starting date..
        /// </summary>
        public static string ToolTip_Account_StartingBalance {
            get {
                return ResourceManager.GetString("ToolTip_Account_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the aggregation is switched on, then the categories will add the values of their subcategories on top of their own..
        /// </summary>
        public static string ToolTip_BudgetOverview_Aggregates {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_Aggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this date picker to jump to an arbitrary month (day is irrelevant)..
        /// </summary>
        public static string ToolTip_BudgetOverview_JumpToMonth {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_JumpToMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift one month backward.
        /// </summary>
        public static string ToolTip_BudgetOverview_ShiftMonthBackward {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_ShiftMonthBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift one month forward.
        /// </summary>
        public static string ToolTip_BudgetOverview_ShiftMonthForward {
            get {
                return ResourceManager.GetString("ToolTip_BudgetOverview_ShiftMonthForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month offset  shifts on which month the income is active.
        ///For example a month offset one will shift the income to the next month, minus one to the previous..
        /// </summary>
        public static string ToolTip_Category_MonthOffset {
            get {
                return ResourceManager.GetString("ToolTip_Category_MonthOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a superior category is selected, then the new category will be appended as a subcategory..
        /// </summary>
        public static string ToolTip_Category_SuperiorCategory {
            get {
                return ResourceManager.GetString("ToolTip_Category_SuperiorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button in this column to delete the element of the corresponding row..
        /// </summary>
        public static string ToolTip_DeleteRow {
            get {
                return ResourceManager.GetString("ToolTip_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to merge one category to another, drag the merge icon from this column in the source row and drop it on the target row.
        ///The target category will get assigned to all account entries of the source category and inherit all the subcategories.
        ///If a pair of the subcategories has the same name, then the subcategory of the  source category is automatically renamed (number is appended)..
        /// </summary>
        public static string ToolTip_MergeToCategory {
            get {
                return ResourceManager.GetString("ToolTip_MergeToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to merge one flag to another, drag the merge icon from this column in the source row and drop it on the target row.
        ///The target flag  will get assigned to all account entries of the source flag and keep its color..
        /// </summary>
        public static string ToolTip_MergeToFlag {
            get {
                return ResourceManager.GetString("ToolTip_MergeToFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to merge one income category to another, drag the merge icon from this column in the source row and drop it on the target row.
        ///The target income category will get assigned to all account entries of the source income category and keep its month offset..
        /// </summary>
        public static string ToolTip_MergeToIncomeCategory {
            get {
                return ResourceManager.GetString("ToolTip_MergeToIncomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to merge one payee to another, drag the merge icon from this column in the source row and drop it on the target row.
        ///The target payee will get assigned to all account entries of the source payee..
        /// </summary>
        public static string ToolTip_MergeToPayee {
            get {
                return ResourceManager.GetString("ToolTip_MergeToPayee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source-Account.
        /// </summary>
        public static string ToolTip_Symbol_FromAccount {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income-Category.
        /// </summary>
        public static string ToolTip_Symbol_IncomeCategory {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_IncomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income-Transaction.
        /// </summary>
        public static string ToolTip_Symbol_IncomeTransaction {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_IncomeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click in order to see and edit the subtransactions..
        /// </summary>
        public static string ToolTip_Symbol_SplitTransaction {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_SplitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target-Account.
        /// </summary>
        public static string ToolTip_Symbol_ToAccount {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string ToolTip_Symbol_Transaction {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string ToolTip_Symbol_Transfer {
            get {
                return ResourceManager.GetString("ToolTip_Symbol_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account which owns the entry..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Account {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category determines your personal purpose of this entry.
        ///Because they maybe hierarchical the whole hierarchy path is shown in the tooltip.
        ///
        ///In case the entry is a transfer, the target-account is filled in here..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Category {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If necessary the check number can be filled in here..
        /// </summary>
        public static string ToolTip_TransGrid_Header_CheckNumber {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This checkmark can be used in order to separate finished entries and entries which still require editing.
        ///The overall sums can be observed in separate manner in the tooltip of the balance..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Cleared {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date on which the entry is active..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Date {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flag marks an entry visually by color and is completely optional..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Flag {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The memo is intended as an arbitrary description of the entry..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Memo {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paid or the paying person of this entry is filled in here.
        ///
        ///In case the entry is a transfer, the source-account is filled in here..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Payee {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbols indicate the type of the account entry..
        /// </summary>
        public static string ToolTip_TransGrid_Header_S {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An income entry marks a transaction which is considered as income..
        /// </summary>
        public static string ToolTip_TransGrid_Header_S_Income {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction lets money flow out of or into the account..
        /// </summary>
        public static string ToolTip_TransGrid_Header_S_Transaction {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transfer passes money from one account to another..
        /// </summary>
        public static string ToolTip_TransGrid_Header_S_Transfer {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_S_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the entry..
        /// </summary>
        public static string ToolTip_TransGrid_Header_Sum {
            get {
                return ResourceManager.GetString("ToolTip_TransGrid_Header_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не соответствует формату валюты.
        /// </summary>
        public static string ValidationRule_Currency {
            get {
                return ResourceManager.GetString("ValidationRule_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение выходит за пределы: [ {0} .. {1} ]!.
        /// </summary>
        public static string ValidationRule_CurrencyLongRange {
            get {
                return ResourceManager.GetString("ValidationRule_CurrencyLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле ввода не может быть пустым!.
        /// </summary>
        public static string ValidationRule_NoNull {
            get {
                return ResourceManager.GetString("ValidationRule_NoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу не существует!.
        /// </summary>
        public static string ValidationRule_NotExistingFilePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка для сохранения не существует!.
        /// </summary>
        public static string ValidationRule_NotExistingSavePath {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла для сохранения отсутствует!.
        /// </summary>
        public static string ValidationRule_NotExistingSavePath_EmptyName {
            get {
                return ResourceManager.GetString("ValidationRule_NotExistingSavePath_EmptyName", resourceCulture);
            }
        }
    }
}
