name: Build & release app on release tag

on:
  push:
    tags:
    - 'v69.*.*'

jobs:
  build:
    runs-on: windows-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 5.0.x
    - run: dotnet build --configuration Release
    - run: |
        cd Composition.Wpf.Program/bin/Release/net5.0-windows
        tar -czf ../../../../BFF_${GITHUB_REF/refs\/tags\//}.tar.gz *
        cd ../../../..
      shell: bash
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BFF_*.tar.gz
      env:
        GITHUB_TOKEN: ${{github.token}}
