name: Build & release app on release tag

on:
  push:
    tags:
    - 'v69.*.*'

jobs:
  build:
    runs-on: windows-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 5.0.x
    - run: dotnet build --configuration Release
    - run: tar -czf artifacts/BFF_${GITHUB_REF/refs\/tags\//}.tar.gz Composition.Wpf.Program/bin/Release/net5.0-windows/
      shell: bash
    - run: gh release create ${GITHUB_REF/refs\/tags\//} artifacts/BFF_${GITHUB_REF/refs\/tags\//}.tar.xz
      shell: bash
